### ISSUE TITLE
Startup instructions are not complete.

### ISSUE THREAD

**Issue by abaljeu** [onshape-public/app-gltf-viewer#20]
I managed with difficulty and web help to reach step 12.  This currently has me stuck:

12. Commit your (local) configuration changes, and push to Heroku. This will start a build process, after which your application will be up and running.
`git commit -am "Updated configuration." && git push heroku master`. If you would like to watch the log as the build is running you can run `heroku logs --tail`.

$ git commit -am "Updated configuration." && git push heroku master
[dependabot/npm_and_yarn/redis-3.1.1 8dc1825] Updated configuration.
 2 files changed, 9 insertions(+), 5 deletions(-)
error: src refspec master does not match any
error: failed to push some refs to 'https://git.heroku.com/cryptic-everglades-60081.git'

**Comment by abaljeu** [comment]
or maybe somehow the heroku create command screwed up for me?

**Comment by ron-onshape** [comment]
It looks like the branch you're working in is `dependabot/npm_and_yarn/redis-3.1.1` - in this case you likely want to push that branch instead of `master`.

**Comment by ron-onshape** [comment]
Upon further investigation, this was caused by Github picking a new branch in the mirror. The "trunk" branch in the source repository was named `master` - and Github no longer automatically recognizes that as the default branch. The `master` branch has now been renamed `main`, and following the setup instructions now behaves correctly.

You can [follow these instructions](https://github.com/github/renaming#renaming-existing-branches) to change the name in your mirror, and you can also set it as your default branch in your repository settings.
